layout_spectrum: 0
color:
  saturation: 0.8440861
  brandStrength: 0.6233538
  lightness: 0.8657689
  rhythmicContrast: 0.2221608
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
typography_spectrum: 0.2043011
name: Gym Fly
